var searchData=
[
  ['tan_5ffun',['tan_fun',['../d7/d4d/structstan_1_1math_1_1tan__fun.html',1,'stan::math']]],
  ['tan_5fvari',['tan_vari',['../de/da8/classstan_1_1math_1_1internal_1_1tan__vari.html',1,'stan::math::internal']]],
  ['tanh_5ffun',['tanh_fun',['../db/d95/structstan_1_1math_1_1tanh__fun.html',1,'stan::math']]],
  ['tanh_5fvari',['tanh_vari',['../d8/d26/classstan_1_1math_1_1internal_1_1tanh__vari.html',1,'stan::math::internal']]],
  ['tgamma_5ffun',['tgamma_fun',['../df/d28/structstan_1_1math_1_1tgamma__fun.html',1,'stan::math']]],
  ['tgamma_5fvari',['tgamma_vari',['../df/de6/classstan_1_1math_1_1internal_1_1tgamma__vari.html',1,'stan::math::internal']]],
  ['trace_5fgen_5fquad_5fform_5fvari',['trace_gen_quad_form_vari',['../df/d4f/classstan_1_1math_1_1internal_1_1trace__gen__quad__form__vari.html',1,'stan::math::internal']]],
  ['trace_5fgen_5fquad_5fform_5fvari_5falloc',['trace_gen_quad_form_vari_alloc',['../db/dd1/classstan_1_1math_1_1internal_1_1trace__gen__quad__form__vari__alloc.html',1,'stan::math::internal']]],
  ['trace_5finv_5fquad_5fform_5fldlt_5fimpl',['trace_inv_quad_form_ldlt_impl',['../d7/de4/classstan_1_1math_1_1internal_1_1trace__inv__quad__form__ldlt__impl.html',1,'stan::math::internal']]],
  ['trace_5finv_5fquad_5fform_5fldlt_5fvari',['trace_inv_quad_form_ldlt_vari',['../db/d3c/classstan_1_1math_1_1internal_1_1trace__inv__quad__form__ldlt__vari.html',1,'stan::math::internal']]],
  ['trace_5fquad_5fform_5fvari',['trace_quad_form_vari',['../d8/d11/classstan_1_1math_1_1internal_1_1trace__quad__form__vari.html',1,'stan::math::internal']]],
  ['trace_5fquad_5fform_5fvari_5falloc',['trace_quad_form_vari_alloc',['../dd/d19/classstan_1_1math_1_1internal_1_1trace__quad__form__vari__alloc.html',1,'stan::math::internal']]],
  ['trigamma_5ffun',['trigamma_fun',['../dd/dc0/structstan_1_1math_1_1trigamma__fun.html',1,'stan::math']]],
  ['trunc_5ffun',['trunc_fun',['../d7/dc2/structstan_1_1math_1_1trunc__fun.html',1,'stan::math']]],
  ['trunc_5fvari',['trunc_vari',['../da/dee/classstan_1_1math_1_1internal_1_1trunc__vari.html',1,'stan::math::internal']]],
  ['tuning_5fstruct',['tuning_struct',['../db/d9c/structstan_1_1math_1_1opencl__context__base_1_1tuning__struct.html',1,'stan::math::opencl_context_base']]]
];
